{
 "title": "Tablero principal",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Volumen FA-02A",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ParametrosProceso\")\n  |> filter(fn: (r) => r[\"_field\"] == \"nivel_litros\")\n  |> filter(fn: (r) => r[\"equipo_id\"] == \"FA-02A\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Flujo Alimentación",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "L/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ParametrosProceso\")\n  |> filter(fn: (r) => r[\"_field\"] == \"flujo_lh\")\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"MF-1.1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Volumen FA-04",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ParametrosProceso\")\n  |> filter(fn: (r) => r[\"_field\"] == \"nivel_litros\")\n  |> filter(fn: (r) => r[\"equipo_id\"] == \"FA-04\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Volumen FA-06B",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ParametrosProceso\")\n  |> filter(fn: (r) => r[\"_field\"] == \"nivel_litros\")\n  |> filter(fn: (r) => r[\"equipo_id\"] == \"FA-06B\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Flujo Alimentación",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "L/h" } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ParametrosProceso\")\n  |> filter(fn: (r) => r[\"_field\"] == \"flujo_lh\")\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"MF-1.1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Volumen FA-01",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ParametrosProceso\")\n  |> filter(fn: (r) => r[\"_field\"] == \"nivel_litros\")\n  |> filter(fn: (r) => r[\"equipo_id\"] == \"FA-01\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Volumen FA-06A",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ParametrosProceso\")\n  |> filter(fn: (r) => r[\"_field\"] == \"nivel_litros\")\n  |> filter(fn: (r) => r[\"equipo_id\"] == \"FA-06A\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Volumen FA-09",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensores\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ParametrosProceso\")\n  |> filter(fn: (r) => r[\"_field\"] == \"nivel_litros\")\n  |> filter(fn: (r) => r[\"equipo_id\"] == \"FA-09\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}